language: java

jdk:
  - openjdk14

sudo: false

env:

  global:

    CODECOV_TOKEN="47c6f743-0831-42c6-8c9c-caffb0244e42"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - Mishail.avram@mail.ru
    on_success: never # default: change
    on_failure: always # default: always